### ISSUE TITLE
FYI: `Characteristic {char_specifier} was not found` with old firmware

### ISSUE THREAD

**Issue by ar-jan** [kbre93/every-breath-you-take#14]
Documenting in case anyone runs into this:

```
Found Polar device
Model Number: H10
...
File: bleak/__init__.py", line 769, in write_gatt_char
    raise BleakError("Characteristic {char_specifier} was not found!")
bleak.exc.BleakError: Characteristic {char_specifier} was not found!
```

This was fixed by updating the firmware (using Polar Flow, Polar Beats did not show the update).

**Comment by kbre93** [comment]
Thanks @ar-jan, I've updated the README to mention the use of Firmware 5.0.0 or later

**Comment by fabiankirsch** [comment]
@ar-jan to which firmware did you update to? 

firmware 5.0.0 doesn't seem to be available for the h10: https://support.polar.com/en/updates/#h-10 

I'm currently on 3.0.47 and with that I get the same error.

**Comment by ar-jan** [comment]
If I have my notes right, I think I updated firmware from 2.1.9 to 3.2.0. Iirc this seemed to work with this app, but I had failures happen during the firmware upgrade and it turned out I'd bricked my H10 (doesn't connect to phone in any way anymore). I would not recommend a firmware upgrade unless you still have full warranty. Polar support was useless.

**Comment by fabiankirsch** [comment]
I also kind of bricked it, because I ran the firmware update with an android 13 phone and nothing worked anymore (not even polar beat), and upgrading with an iphone also didn't work. but now i tried with an android 15 phone and the firmware update went through (using polar beat), and now everything works including this app here 🥳 

the polar h10 is now on firmware version 3.3.1 (according to the polar beat app), but in the terminal (when i start the "don't hold your breath" app, not this one), it says this:

```
Model Number: H10
Manufacturer Name: Polar Electro Oy
Serial Number: E75A7C1E
Address: 00:22:D0:E7:5A:7C
Battery Level: 100%
Firmware Revision: 5.0.0
Hardware Revision: 00760690.03
Software Revision: 3.3.1
```

So I guess this is where the 5.0.0. is coming from.
